name: "Terragrunt Plan"
description: "Runs Terragrunt plan"

inputs:
  account_id:
    description: "AWS Account ID"
    required: true
  aws-region:
    description: 'AWS Region for the State Bucket and Resources'
    default: eu-west-2
    required: false
    type: string
  github-environment:
    description: 'The name of your AWS environment. Create an environment secret called ACCOUNT_ID, also.'
    required: false
    default: 'placeholder'
    type: string
  role-to-assume:
    description: 'AWS Role name for OIDC'
    required: true
    type: string
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.7.0"
  terragrunt-version:
    description: "Terragrunt version to use"
    required: false
    default: "0.59.6"
  working-directory:
    description: "Directory of the Terragrunt code"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      name: Configure AWS IdP Credentials
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role-to-assume }}
        role-session-name: GitHubActions
        retry-max-attempts: 5
        aws-region: ${{ inputs.aws-region }}

    - name: Download Terragrunt Folders
      uses: actions/download-artifact@v4
      with:
        name: terragrunt-files
        path: ${{ github.workspace }}

    - name: Fix Binary Permissions
      shell: bash
      # This restores the +x bit that artifacts strip away
      run: |
        find . -name "terraform-provider-*" -type f -exec chmod +x {} \;

    - name: Create output folder
      shell: bash
      run: mkdir -p $GITHUB_WORKSPACE/outputs/${{ inputs.path }}

    - name: Debug
      shell: bash
      run: |
        find . -name ".terragrunt-cache" -type d

    - name: Terragrunt Plan
      id: tg_plan
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ inputs.terraform-version }}
        tg_version: ${{ inputs.terragrunt-version }}
        tg_dir: ${{ inputs.working-directory }}/terraform/environment/${{ inputs.github-environment }}
        tg_command: 'run-all plan --terragrunt-out-dir /github/workspace/outputs/terraform/environment/${{ inputs.github-environment }} --terragrunt-json-out-dir /github/workspace/outputs/terraform/environment/${{ inputs.github-environment }} -detailed-exitcode'
      env:
        env_name: ${{ inputs.github-environment }}
        TF_VAR_source-repo: "${{ github.server_url }}/${{ github.repository }}"
        TERRAGRUNT_DOWNLOAD: "${{ github.workspace }}/.terragrunt-cache"


    - name: Set Plan Outcome
      shell: bash
      if: always()
      run: |
        if [ "${{ steps.tg_plan.outcome }}" == "success" ] || [ "${{ steps.tg_plan.outputs.exit_code }}" == "2" ]; then
          echo "Plan_Outcome=success" >> $GITHUB_ENV
          if [ "${{ steps.tg_plan.outputs.exit_code }}" == "2" ]; then
            echo "Changes_Detected=true" >> $GITHUB_ENV
          else
            echo "Changes_Detected=false" >> $GITHUB_ENV
          fi
        else
          echo "Plan_Outcome=failed" >> $GITHUB_ENV
        fi

    - name: Upload Plan Artifacts
      if: env.Plan_Outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: terragrunt-plan-file
        path: |
          ${{ inputs.working-directory }}/**/tfplan
          ${{ inputs.working-directory }}/**/.terragrunt-cache/
          ${{ inputs.working-directory }}/**/.terraform.lock.hcl
        include-hidden-files: true
        retention-days: 1
