name: "Terragrunt Plan"
description: "Runs Terragrunt plan"

inputs:
  account_id:
    description: "AWS Account ID"
    required: true
  aws-region:
    description: 'AWS Region for the State Bucket and Resources'
    default: eu-west-2
    required: false
    type: string
  github-environment:
    description: 'The name of your AWS environment. Create an environment secret called ACCOUNT_ID, also.'
    required: false
    default: 'placeholder'
    type: string
  role-to-assume:
    description: 'AWS Role name for OIDC'
    required: true
    type: string
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.7.0"
  terragrunt-version:
    description: "Terragrunt version to use"
    required: false
    default: "0.59.6"
  working-directory:
    description: "Directory of the Terragrunt code"
    required: false
    default: "."
outputs:
  tg-plan-changes:
    description: "Whether the plan found infrastructure changes"
    value: ${{ steps.parse-plan.outputs.tg-plan-changes }}

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      name: Configure AWS IdP Credentials
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role-to-assume }}
        role-session-name: GitHubActions
        retry-max-attempts: 5
        aws-region: ${{ inputs.aws-region }}

    - name: Download Terragrunt Folders
      uses: actions/download-artifact@v4
      with:
        name: terragrunt-files
        path: ${{ inputs.working-directory }}

    - name: Fix Permissions
      shell: bash
      run: |
        sudo chown -R $USER:$USER ${{ github.workspace }}
        sudo find ${{ github.workspace }} -type d -exec chmod 755 {} +
        echo "Searching for provider binaries to fix permissions..."
        sudo find ${{ github.workspace }} -name "terraform-provider-*" -type f -exec chmod +x {} \;
        echo "Permissions restoration complete."

    - name: Terragrunt Plan
      id: tg_plan
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ inputs.terraform-version }}
        tg_version: ${{ inputs.terragrunt-version }}
        tg_dir: ${{ inputs.working-directory }}/${{ inputs.working-directory }}
        tg_command: 'run-all plan'
      env:
        env_name: ${{ inputs.github-environment }}
        TF_VAR_source-repo: "${{ github.server_url }}/${{ github.repository }}"
        TERRAGRUNT_DOWNLOAD: .terragrunt-cache

    - name: Parse Plan Output
      shell: bash
      id: parse-plan
      run: |
        text="$(cat <<'EOF_TEXT'
        ${{ steps.tg_plan.outputs.tg_action_output }}
        EOF_TEXT
        )"

        sub1='Changes to Outputs:'
        sub2='Plan:'

        if echo "$text" | grep -qF -- "$sub1" || echo "$text" | grep -qF -- "$sub2"; then
          echo 'Changes detected (based on plan output patterns)'
          echo "tg-plan-changes=true" >> $GITHUB_OUTPUT
        else
          echo 'No changes detected in plan output'
          echo "tg-plan-changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Fix Permissions
      shell: bash
      run: |
        sudo chown -R $USER:$USER .
        find . -type d -exec chmod 755 {} +
        find . -type f -name "terraform-provider-*" -exec chmod +x {} +

    - name: Upload Plan Artifacts
      if: steps.parse-plan.outputs.tg-plan-changes == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: terragrunt-plan-file
        path: |
          ${{ inputs.working-directory }}/**/tfplan
          ${{ inputs.working-directory }}/**/.terragrunt-cache/
          ${{ inputs.working-directory }}/**/.terraform.lock.hcl
        include-hidden-files: true
        retention-days: 1
