name: Standard Terragrunt Pipeline

on:
  workflow_call:
    inputs:
      apply-branch:
        description: 'If you want to apply resources to a branch that is not main'
        required: false
        type: string
        default: 'main'
      aws-region:
        description: 'AWS Region for the State Bucket and Resources'
        default: eu-west-2
        required: false
        type: string
      github-environment:
        description: 'The name of your AWS environment. Create an environment secret called ACCOUNT_ID, also.'
        required: false
        default: 'placeholder'
        type: string
      role-to-assume:
        description: 'AWS Role name for OIDC'
        required: true
        type: string
      runner:
        description: 'Runner label(s) to run the pipeline job on, e.g. a self-hosted runner label'
        required: false
        default: 'ubuntu-latest'
        type: string
      state-bucket:
        description: 'Name of the S3 bucket for Terraform State'
        required: true
        type: string
      state-dynamodb-table:
        description: 'Name of the DynamoDB table'
        required: false
        default: ''
        type: string
      state-key:
        description: "Where you want the state key to be"
        required: false
        type: string
        default: 'terraform.tfstate'
      terraform-version:
        description: 'Terraform version to use'
        required: false
        default: '1.7.0'
        type: string
      terragrunt-version:
        description: 'Terragrunt version to use'
        required: false
        default: '0.59.6'
        type: string
      terragrunt-parallelism:
        description: 'Max number of concurrent Terragrunt modules'
        required: false
        default: '4'
        type: string
      working-directory:
        description: 'Directory containing main.tf'
        required: false
        default: '.'
        type: string
      enable-checkov-scan:
        description: 'Set to true to scan the generated tfplan with Checkov between Plan and Apply'
        required: false
        default: false
        type: boolean
    secrets:
      account_id:
        required: true
      EXEMPTIONS_APP_ID:
        description: Exemptions secret applied by the Core Cloud team when exceptions are approved and required.
        required: false
      EXEMPTIONS_APP_PRIVATE_KEY:
        description: Exemptions secret applied by the Core Cloud team when exceptions are approved and required.
        required: false

permissions:
  contents: read
  pull-requests: write
  id-token: write
  security-events: write
  actions: read

jobs:
  terragrunt-standard-pipeline:
    name: "Terragrunt Standard Pipeline"
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.github-environment }}

    permissions:
      contents: read
      pull-requests: write
      id-token: write
      security-events: write
      actions: read

    outputs:
      result: ${{ steps.fmt.outcome }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terragrunt Init
        id: init
        uses: Home-Office-Digital/core-cloud-workflow-terragrunt-actions/actions/init@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          state-bucket: ${{ inputs.state-bucket }}
          state-dynamodb-table: ${{ inputs.state-dynamodb-table }}
          state-key: ${{ inputs.state-key }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}
          terragrunt-parallelism: ${{ inputs.terragrunt-parallelism }}
          working-directory: ${{ inputs.working-directory }}

      - name: Fix Permissions for Runner
        shell: bash
        run: sudo chown -R $USER:$USER .

      - name: Cache Terraform Providers
        uses: actions/cache@v4
        with:
          path: .terraform.d/plugin-cache
          key: terraform-providers-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            terraform-providers-${{ runner.os }}-

      - name: Terragrunt Fmt
        id: fmt
        uses: Home-Office-Digital/core-cloud-workflow-terragrunt-actions/actions/fmt@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Terragrunt Validate
        id: validate
        if: success() || failure()
        uses: Home-Office-Digital/core-cloud-workflow-terragrunt-actions/actions/validate@main
        with:
          github-environment: ${{ inputs.github-environment }}
          working-directory: ${{ inputs.working-directory }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}
          terragrunt-parallelism: ${{ inputs.terragrunt-parallelism }}

      - name: Terragrunt Plan
        id: plan
        uses: Home-Office-Digital/core-cloud-workflow-terragrunt-actions/actions/plan@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}
          terragrunt-parallelism: ${{ inputs.terragrunt-parallelism }}
          working-directory: ${{ inputs.working-directory }}
          enable-checkov-scan: ${{ inputs.enable-checkov-scan }}

      - name: Fix Permissions for Runner
        if: inputs.enable-checkov-scan == true
        shell: bash
        run: sudo chown -R $USER:$USER .

      - name: Checkov Scan (Plan Files)
        id: checkov
        if: inputs.enable-checkov-scan == true
        uses: Home-Office-Digital/core-cloud-workflow-checkov-sast-scan/actions/tfplan@main
        with:
          plan_role: ''
          existing-plan-dir: ${{ steps.plan.outputs.plan-output-dir }}
          path: ${{ inputs.working-directory }}
          env_name: ${{ inputs.github-environment }}
          account_id: ${{ secrets.ACCOUNT_ID }}
          TF_VAR_source-repo: "${{ github.server_url }}/${{ github.repository }}"
          EXEMPTIONS_APP_ID: ${{ secrets.EXEMPTIONS_APP_ID }}
          EXEMPTIONS_APP_PRIVATE_KEY: ${{ secrets.EXEMPTIONS_APP_PRIVATE_KEY }}

      - name: Terragrunt Apply
        id: apply
        if: steps.plan.outputs.tg-plan-changes == 'true' && github.ref_name == inputs.apply-branch
        uses: Home-Office-Digital/core-cloud-workflow-terragrunt-actions/actions/apply@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          apply-branch: ${{ inputs.apply-branch }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}
          terragrunt-parallelism: ${{ inputs.terragrunt-parallelism }}
          working-directory: ${{ inputs.working-directory }}

      - name: Terragrunt Destroy Plan
        id: destroy-plan
        uses: Home-Office-Digital/core-cloud-workflow-terragrunt-actions/actions/destroy-plan@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}
          terragrunt-parallelism: ${{ inputs.terragrunt-parallelism }}
          working-directory: ${{ inputs.working-directory }}

      - name: Terragrunt Destroy Apply
        id: destroy-apply
        if: steps.destroy-plan.outputs.tg-destroy-plan-changes == 'true' && github.ref_name == inputs.apply-branch
        uses: Home-Office-Digital/core-cloud-workflow-terragrunt-actions/actions/destroy-apply@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          apply-branch: ${{ inputs.apply-branch }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}
          terragrunt-parallelism: ${{ inputs.terragrunt-parallelism }}
          working-directory: ${{ inputs.working-directory }}
