name: Standard Terragrunt Pipeline

on:
  workflow_call:
    inputs:
      aws-region:
        description: 'AWS Region for the State Bucket and Resources'
        default: eu-west-2
        required: false
        type: string
      github-environment:
        description: 'The name of your AWS environment. Create an environment secret called ACCOUNT_ID, also.'
        required: false
        default: 'placeholder'
        type: string
      role-to-assume:
        description: 'AWS Role name for OIDC'
        required: true
        type: string
      state-bucket:
        description: 'Name of the S3 bucket for Terraform State'
        required: true
        type: string
      state-dynamodb-table:
        description: 'Name of the DynamoDB table'
        required: false
        default: ''
        type: string
      state-key:
        description: "Where you want the state key to be"
        required: false
        type: string
        default: 'terraform.tfstate'
      terraform-version:
        description: 'Terraform version to use'
        required: false
        default: '1.7.0'
        type: string
      terragrunt-version:
        description: 'Terragrunt version to use'
        required: false
        default: '0.59.6'
        type: string
      working-directory:
        description: 'Directory containing main.tf'
        required: false
        default: '.'
        type: string
    secrets:
      account_id:
        required: true

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  quality-checks:
    name: "Quality & Security"
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}

    permissions:
      contents: read
      pull-requests: write
      id-token: write

    outputs:
      result: ${{ steps.quality-checks.outcome }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terragrunt Init
        id: init
        uses: UKHomeOffice/core-cloud-workflow-terragrunt-actions/actions/init@main
        with:
          account_id: ${{ secrets.ACCOUNT_ID }}
          aws-region: ${{ inputs.aws-region }}
          github-environment: ${{ inputs.github-environment }}
          role-to-assume: ${{ inputs.role-to-assume }}
          state-bucket: ${{ inputs.state-bucket }}
          state-dynamodb-table: ${{ inputs.state-dynamodb-table }}
          state-key: ${{ inputs.state-key }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Terragrunt Fmt
        id: quality-checks
        uses: UKHomeOffice/core-cloud-workflow-terragrunt-actions/actions/fmt@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Terragrunt Validate
        if: success() || failure()
        uses: UKHomeOffice/core-cloud-workflow-terragrunt-actions/actions/validate@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terraform-version: ${{ inputs.terraform-version }}
          terragrunt-version: ${{ inputs.terragrunt-version }}

# # TODO: TFLint is not part of the official terraform CLI and is more complex. Suggest keeping that in separate repo and pointing to it here, with the ability to disable
#       - name: TFLint
#         if: success() || failure()
#         uses: UKHomeOffice/core-cloud-workflow-tflint-scan@main

#       - name: Terraform Plan
#         id: plan
#         uses: UKHomeOffice/core-cloud-workflow-terraform-actions/actions/plan@main
#         with:
#           account_id: ${{ secrets.ACCOUNT_ID }}
#           github-environment: ${{ inputs.github-environment }}
#           aws-region: ${{ inputs.aws-region }}
#           role-to-assume: ${{ inputs.role-to-assume }}

#       - name: Terraform Apply
#         id: apply
#         if: github.ref_name == 'main'
#         uses: UKHomeOffice/core-cloud-workflow-terraform-actions/actions/apply@main
#         with:
#           account_id: ${{ secrets.ACCOUNT_ID }}
#           github-environment: ${{ inputs.github-environment }}
#           aws-region: ${{ inputs.aws-region }}
#           role-to-assume: ${{ inputs.role-to-assume }}
